# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0b28ed44be51b4af36b74460c821803d0e7b9e7b0205c6b39bd423a1cfa28aec727d22cbd4ce92ba67d28df2fd95d0ab889ee1a83cb9fea26a708371bfed9c2

test:
  secret_key_base: c3c6766f4b195837f5722ee3ddf83b9abb40c852689e860f4740f4352f2d0851c1557d03f94103a1a8ec355f797db3ca9393b9830639da24140089bfd23b9bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
